Added web socket routing
Diesel-Jeans/signal pull request #106
Opened 2024-11-12 12:19 UTC by Darkros1245

Added web socket routing.
We  have to figure out how to delete messages after they have been sent.

2024-11-12 12:42 UTC, MJHC reviewed
check if http endpoint still works after changed func signature

2024-11-12 13:46 UTC, MJHC approved these changes
![okay](https://github.com/user-attachments/assets/3ccb308b-7a77-4b0e-b331-cb302725e901)

2024-11-12 13:49 UTC, andreasalstrup requested changes
test managers::websocket::connection::test::test_on_receive_request ... FAILED

failures:

---- managers::websocket::connection::test::test_on_receive_request stdout ----
thread 'managers::websocket::connection::test::test_on_receive_request' panicked at server/src/managers/websocket/connection.rs:566:14:
called `Result::unwrap()` on an `Err` value: "Send failed"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    managers::websocket::connection::test::test_on_receive_request

test result: FAILED. 62 passed; 1 failed; 9 ignored; 0 measured; 0 filtered out; finished in 2.19s

2024-11-12 13:49 UTC, MJHC commented
![no](https://github.com/user-attachments/assets/43a6cc4d-9146-4923-b5da-2c31b6fa9c9d)

2024-11-12 13:54 UTC, andreasalstrup commented on server/src/managers/websocket/connection.rs
> +            ));
Der mangler?

`.await`

2024-11-14 08:37 UTC, MJHC commented on server/src/managers/websocket/connection.rs
> +                    StatusCode::INTERNAL_SERVER_ERROR.as_u16() as u32,
only take statuscode one time

2024-11-14 08:38 UTC, MJHC commented on server/src/managers/websocket/connection.rs
> +    async fn test_on_receive_response() {
add a test that tests that one client can send a message to another, by inserting two clients into the websocketmanager and having alice's sender send a message and then bobs receiver receive a message after a short sleep

2024-11-14 12:24 UTC, MJHC approved these changes
![okay](https://github.com/user-attachments/assets/5f1df257-98d8-4a43-94ff-88cb8cfd931d)

2024-11-14 12:52 UTC, Laursen79 requested changes

2024-11-14 12:52 UTC, Laursen79 commented on server/src/account.rs
>  impl Device {
brug bon?

2024-11-14 12:52 UTC, Laursen79 commented on server/src/server.rs
> +        message: "a".to_owned(),
Hvad??

2024-11-14 12:52 UTC, Laursen79 commented on server/src/server.rs
> +        message: "b".to_owned(),
Hvad??

2024-11-14 12:52 UTC, Laursen79 commented on server/src/server.rs
> +        state.message_manager.insert(&address, &mut envelope).await; // TODO: Remember to check for
Todo?

2024-11-14 12:52 UTC, Laursen79 commented on server/src/server.rs
>      Json(payload): Json<SignalMessages>, // TODO: Multiple messages could be sent at one time
```suggestion
    Json(payload): Json<SignalMessages>,
```

2024-11-14 12:52 UTC, Laursen79 commented on server/src/server.rs
> +            //    .await;
What is this?

2024-11-14 13:29 UTC, Laursen79 approved these changes

2024-11-14 13:31 UTC, MJHC approved these changes
![sticker(1)](https://github.com/user-attachments/assets/c647121a-d92a-4ac2-9133-dfb54a88588a)

2024-11-14 13:33 UTC, andreasalstrup approved these changes

2024-11-14 13:34 UTC, merged