Formatted all the sql statements
Diesel-Jeans/signal pull request #112
Opened 2024-11-14 12:12 UTC by Mikkel-Boje

Formatted based on https://sqlformat.org/ as a standart.

2024-11-14 12:16 UTC, andreasalstrup submitted a review, later dismissed
Very nice!

2024-11-14 12:38 UTC, Darkros1245 requested changes
NOPE

2024-11-14 12:43 UTC, Darkros1245 approved these changes
🤮🤮🤮

2024-11-14 12:49 UTC, Darkros1245 approved these changes

2024-11-15 07:52 UTC, andreasalstrup approved these changes

2024-11-15 08:35 UTC, merged