Bump tonic version to avoid vulnerability
Diesel-Jeans/signal pull request #22
Opened 2024-10-03 07:14 UTC by Laursen79

2024-10-03 08:10 UTC, Mikkel-Boje approved these changes

2024-10-03 08:40 UTC, t-lohse commented
I actually need this vulnerability, pls don't merge this

2024-10-04 08:31 UTC, UnluckyBird approved these changes

2024-10-04 11:46 UTC, t-lohse commented
@Laursen79 stop them!
![image](https://github.com/user-attachments/assets/44887bf2-765f-4cce-8d8c-06be8e591fa2)

2024-10-04 11:48 UTC, t-lohse requested changes

2024-10-04 11:48 UTC, t-lohse commented on client/Cargo.toml
> +tonic-build = "0.12.3"
```suggestion
tonic-build = "0.12.2"
```

2024-10-04 11:49 UTC, t-lohse requested changes
plz

2024-10-04 11:49 UTC, t-lohse commented on common/Cargo.toml
> +tonic = "0.12.3"
```suggestion
tonic = "0.12.2"
```

2024-10-04 11:49 UTC, t-lohse commented on common/Cargo.toml
> +tonic-build = "0.12.3"
```suggestion
tonic-build = "0.12.2"
```

2024-10-04 11:49 UTC, t-lohse commented on server/Cargo.toml
> +tonic-build = "0.12.3"
```suggestion
tonic-build = "0.12.2"
```

2024-10-07 07:33 UTC, merged