GET: v2/keys
Diesel-Jeans/signal pull request #42
Opened 2024-10-07 10:17 UTC by Mikkel-Boje

Closes #38
Added the endpoint getting the amount of pre keys available for a specific user.

2024-10-07 12:15 UTC, AOsnes requested changes
Please test your code

2024-10-07 12:15 UTC, AOsnes commented on common/src/web_api.rs
> +    pub key_id: u64,
I would like this change to be reflected in the client key bundles as well

2024-10-08 12:02 UTC, AOsnes approved these changes

2024-10-08 12:06 UTC, alexsteffensen approved these changes
LGTM

2024-10-08 12:06 UTC, merged