Add endpoints and merge database
Diesel-Jeans/signal pull request #49
Opened 2024-10-14 06:56 UTC by Laursen79

2024-10-15 08:17 UTC, AOsnes submitted a review, later dismissed

2024-10-15 12:30 UTC, Darkros1245 requested changes

2024-10-15 12:30 UTC, Darkros1245 commented on client/src/server.rs
> +                ReqType::Delete(value) => "DELETE",
Use _ instead of value

2024-10-15 12:30 UTC, Darkros1245 commented on server/database/init.sql
> +    ('bob', NULL, '1236854bff0ad5aa206f924c9c2ff800681f69df4f6963976f144c1842c2ff1b', '\x053b258970748dff667800108898e390a1dfabd8fa66889748d903c12fbc5c732d'::bytea); -- auth_token = BBBBBB
We should also change this for alice

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/in_memory_db.rs
> +/*
Remove comment

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/in_memory_db.rs
> +        /*
Remove or add comment

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/main.rs
> +#![allow(unused)]
Are we going to need this later?

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/postgres.rs
> +            aci = $1
Add COALESCE

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/postgres.rs
> +            pni = $1
Add COALESCE

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/postgres.rs
> +            AND pni = $2
Add COALESCE

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/postgres.rs
> +                    aci = $2
Add COALESCE

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/postgres.rs
> +                    AND pni = $2
Add COALESCE

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/postgres.rs
> +                    AND pni = $2
Add COALESCE

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/postgres.rs
> +                    AND accounts.pni = $2
Add COALESCE

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/postgres.rs
> +                    AND accounts.pni = $2
Add COALESCE

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/postgres.rs
> +            AND pni = $2
Add COALESCE

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/server.rs
> +    /*
Add or remove comment

2024-10-15 12:30 UTC, Darkros1245 commented on server/src/server.rs
> +    /*
Add or remove comment

2024-10-17 07:50 UTC, UnluckyBird commented on server/database/init.sql
> -    'bob_device', id
Mener at deviceId starter fra 1, hvor 1 betyder det er primary device for brugeren

2024-10-17 07:50 UTC, UnluckyBird commented on server/src/api_error.rs
> +    pub error_code: Option<u32>,
Kommer vi til at bruge errorcode ud over bare statuscode?

2024-10-17 08:37 UTC, Laursen79 commented on server/src/api_error.rs
> +    pub error_code: Option<u32>,
god pointe

2024-10-17 11:43 UTC, Darkros1245 requested changes

2024-10-17 11:43 UTC, Darkros1245 commented on server/database/init.sql
> -);
Remove

2024-10-17 11:43 UTC, Darkros1245 commented on server/database/init.sql
> +-- INSERT INTO
Remove

2024-10-17 11:43 UTC, Darkros1245 commented on server/database/init.sql
> -    AND pni IS NULL;
Remove

2024-10-17 11:43 UTC, Darkros1245 commented on server/src/postgres.rs
> +use crate::{account::Account, database::SignalDatabase};
A genius must have made this code <3

2024-10-17 11:43 UTC, Darkros1245 commented on server/src/server.rs
> +    println!("Get messages")
Nice handling

2024-10-17 11:43 UTC, Darkros1245 commented on server/src/server.rs
>      if let Some(keys) = database
Remove

2024-10-17 11:43 UTC, Darkros1245 commented on server/src/server.rs
> +        /*
Remove

2024-10-17 11:43 UTC, Darkros1245 commented on server/src/server.rs
> +        /*
Remove

2024-10-17 11:47 UTC, Mikkel-Boje requested changes

2024-10-17 11:47 UTC, Mikkel-Boje commented on server/database/init.sql
> +-- CREATE TABLE devices (
Remove

2024-10-17 11:47 UTC, Mikkel-Boje commented on server/database/init.sql
> +-- INSERT INTO
Remove

2024-10-17 11:47 UTC, Mikkel-Boje commented on server/src/database.rs
> +    async fn get_one_time_pre_key_count(&self, account: &ServiceId) -> Result<u32>;
```suggestion
    async fn get_one_time_pre_key_count(&self, service_id: &ServiceId) -> Result<u32>;
```

2024-10-17 11:47 UTC, Mikkel-Boje commented on server/src/database.rs
> +        owner: ProtocolAddress,
```suggestion
        adress: ProtocolAddress,
```

2024-10-17 11:47 UTC, Mikkel-Boje commented on server/src/database.rs
> +    async fn get_one_time_pre_key(&self, owner: ProtocolAddress) -> Result<UploadSignedPreKey>;
```suggestion
    async fn get_one_time_pre_key(&self, adress: ProtocolAddress) -> Result<UploadSignedPreKey>;
```

2024-10-17 11:47 UTC, Mikkel-Boje commented on server/src/postgres.rs
> +            Some(new_aci.service_id_string())
Please remove Some as it adds nothing
```suggestion
            new_aci.service_id_string()
```

2024-10-17 11:47 UTC, Mikkel-Boje commented on server/src/postgres.rs
> +            Some(new_pni.service_id_string())
```suggestion
            new_pni.service_id_string()
```

2024-10-17 11:59 UTC, UnluckyBird requested changes

2024-10-17 11:59 UTC, UnluckyBird commented on server/src/in_memory_db.rs
> +        self.devices
Skal nokk være self.accounts, når det er accounts vi adder? Og hvorfor asserter vi?

2024-10-17 11:59 UTC, UnluckyBird commented on server/src/postgres.rs
> +fn pasrse_to_specific_service_id(service_id: &ServiceId) -> (String, String) {
parse*

2024-10-17 11:59 UTC, UnluckyBird commented on server/src/postgres.rs
> +fn pasrse_to_specific_service_id_from_protocol_address(
parse*

2024-10-17 11:59 UTC, UnluckyBird commented on server/src/server.rs
>  use axum::http::header::{ACCEPT, AUTHORIZATION, CONTENT_LENGTH, CONTENT_TYPE, ORIGIN};
Er det ikke muligt at neste det her use hell lidt, eller bliver fmt sur så?

2024-10-17 11:59 UTC, UnluckyBird commented on server/src/server.rs
> +    if let Err(result) = state
```
    state.database()
        .push_message_queue(address, vec![payload])
        .await
        .map_err(|_| Err(ApiError {
            message: "Could not push the message to message queue.".to_owned(),
            status_code: StatusCode::INTERNAL_SERVER_ERROR,
        }))?
    OK()
```

2024-10-17 12:06 UTC, Mikkel-Boje requested changes

2024-10-17 12:16 UTC, UnluckyBird commented on server/src/database.rs
> +        owner: ProtocolAddress,
address*

2024-10-17 12:16 UTC, UnluckyBird commented on server/src/database.rs
> +    async fn get_one_time_pre_key(&self, owner: ProtocolAddress) -> Result<UploadSignedPreKey>;
address

2024-10-17 12:39 UTC, Mikkel-Boje requested changes

2024-10-17 12:39 UTC, Mikkel-Boje commented on server/src/in_memory_db.rs
> +            .ok_or_else(|| anyhow!("No user exists with ID"))
```suggestion
            .ok_or(anyhow!("No user exists with ID"))
```

2024-10-17 12:46 UTC, UnluckyBird approved these changes
For sure 100% bug free

2024-10-17 12:47 UTC, Darkros1245 approved these changes

2024-10-17 12:47 UTC, Mikkel-Boje approved these changes
Such a stable api, unlucky that the database is so

2024-10-17 12:49 UTC, merged