Adding two endpoints
Diesel-Jeans/signal pull request #52
Opened 2024-10-18 09:16 UTC by Mikkel-Boje

* GET: Keys, fetching a users keys.
* POST: check keys, checking the servers keys vs. the users

2024-10-18 10:07 UTC, MJHC submitted a review, later dismissed
ok

2024-10-21 10:11 UTC, Darkros1245 commented on client/src/key_management/bundle.rs
> +            || bundle.onetime_public_key.is_none()
This should work, right?
```suggestion
            || bundle
            .onetime_public_key
            .is_none()
```

2024-10-21 10:11 UTC, Darkros1245 commented on server/src/server.rs
> +    todo!();
Is this still todo?

2024-10-21 10:11 UTC, Darkros1245 commented on server/src/server.rs
> +//#[debug_handler]
Is this no longer needed?

2024-10-21 10:11 UTC, Darkros1245 commented on server/src/server.rs
>      // TODO: Call `handle_get_keys`
Can't we do that now?

2024-10-21 11:31 UTC, Darkros1245 submitted a review, later dismissed

2024-10-21 12:00 UTC, Darkros1245 approved these changes

2024-10-22 07:39 UTC, UnluckyBird submitted a review, later dismissed

2024-10-24 12:53 UTC, Darkros1245 requested changes
NOT GUT

2024-10-24 12:58 UTC, Darkros1245 approved these changes

2024-10-25 07:18 UTC, Laursen79 approved these changes

2024-10-25 07:19 UTC, merged