Msg cache
Diesel-Jeans/signal pull request #62
Opened 2024-10-21 10:10 UTC by alexsteffensen

2024-10-21 10:39 UTC, Mikkel-Boje requested changes

2024-10-21 10:39 UTC, Mikkel-Boje commented on server/src/server.rs
> +//use deadpool_redis::redis::PushKind::Message;
Remove

2024-10-21 10:39 UTC, Mikkel-Boje commented on server/src/server.rs
> +pub(crate) struct ServerState {
Do we want this to be pub? Shouldn't it only be the "new" function which is public, since we dont want it to be initialized without a call to "new"

2024-10-21 10:39 UTC, Mikkel-Boje commented on server/src/server.rs
> +
Remove?

2024-10-21 10:39 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +}
Remove?

2024-10-21 10:39 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +    //hashmap: HashMap<String, dyn MessageAvailabilityListener>,
rm

2024-10-21 10:39 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +    }
rm for now

2024-10-21 10:39 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +            //event_receiver: Arc::new(Mutex::new(message_rx)),
rm comments

2024-10-25 08:59 UTC, Laursen79 requested changes
Run cargo clippy --fix, pls

2024-10-25 09:15 UTC, Laursen79 requested changes
Cargo clippy --fix pls

2024-10-25 09:15 UTC, Laursen79 commented on server/src/message_cache.rs
> +        message.content = Some("Hello this is a test".as_bytes().to_vec());
```suggestion
        let mut message = Envelope {
            content: Some("Hello this is a test".as_bytes().to_vec()),
            ..Default::default()
        }
```

2024-10-25 09:15 UTC, Laursen79 commented on server/src/server.rs
The server state is going to move into the new managers module.

2024-10-25 09:15 UTC, Mikkel-Boje requested changes

2024-10-25 09:15 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +        for i in (0..messages.len()).step_by(2) {
Can you make a comment on how this actually works. As you said messages are pairs as env, id and you only want the env

2024-10-25 09:15 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +        let message_sort = format!("({}", after_message_id);
```suggestion
        let message_sort = format!("{}", after_message_id);
```

2024-10-25 09:15 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +            envelopes.push(bincode::deserialize(&messages[i]).unwrap());
Please dont unwrap

2024-10-25 09:15 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +        let mut con = self.pool.get().await.unwrap();
```suggestion
        let mut con = self.pool.get().await?;
```

2024-10-25 09:15 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +        // if there is a queue lock key on due to persist of message.
```suggestion
        // if there is a queue lock key on, due to persist of message.
```

2024-10-25 09:15 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +            .unwrap();
```suggestion
        let locked: Option<String> = cmd("GET")
            .arg(queue_lock_key)
            .query_async(&mut con)
            .await?;
```

2024-10-25 09:15 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +        if let Some(lock_key) = locked {
Maybe do a test for the lock

2024-10-25 09:15 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +            .unwrap();
```suggestion
            .await?;
```

2024-10-25 09:15 UTC, Mikkel-Boje commented on server/src/message_cache.rs
> +        let mut conn = self.pool.get().await.unwrap();
```suggestion
        let mut conn = self.pool.get().await?;
```

2024-10-25 09:18 UTC, Laursen79 commented on server/src/message_cache.rs
> +        // if there is a queue lock key on due to persist of message.
Hvad siger den her sætning??

2024-10-25 10:10 UTC, alexsteffensen commented on server/src/message_cache.rs
> +        let _ = dotenv::dotenv();
It is needed, as CI would crash if the let is deleted

2024-10-25 11:33 UTC, Mikkel-Boje approved these changes
:+1:

2024-10-25 11:34 UTC, Laursen79 approved these changes

2024-10-25 11:37 UTC, merged