Made account and key managers
Diesel-Jeans/signal pull request #67
Opened 2024-10-24 11:36 UTC by Darkros1245

2024-10-28 10:56 UTC, MJHC submitted a review, later dismissed
ok

2024-10-28 10:59 UTC, Mikkel-Boje requested changes

2024-10-28 10:59 UTC, Mikkel-Boje commented on server/src/managers/key_manager.rs
>  }
```suggestion
}
```

2024-10-28 11:02 UTC, Laursen79 requested changes

2024-10-29 08:00 UTC, Mikkel-Boje requested changes

2024-10-29 08:11 UTC, Mikkel-Boje approved these changes
:+1:

2024-10-29 08:13 UTC, Laursen79 approved these changes

2024-10-29 08:13 UTC, Mikkel-Boje approved these changes

2024-10-29 08:16 UTC, merged